### ISSUE TITLE
file upload from inside node js

### ISSUE THREAD

**Issue by furryboffin** [onfido/onfido-node#80]
**Upload inside Node JS**
I am trying to use onfido/api Version 2.3.1 in node js V12 with typescript. I used the following code example from the documentation.
```
const buffer = Buffer.from(base64Data, "base64");
const bufferStream = new PassThrough();
bufferStream.end(buffer);

onfido.document.upload({
  applicantId: "<APPLICANT_ID>",
  file: {
    contents: bufferStream,
    filepath: "image.png",
    contentType: "image/png"
  },
  type: "passport"
});
```
I get the following error:

```
/home/node/app/webpack:/quinten/node_modules/follow-redirects/index.js:84
    throw new TypeError("data should be a string, Buffer or Uint8Array");
^
TypeError: data should be a string, Buffer or Uint8Array
    at RedirectableRequest.write (/home/node/app/webpack:/quinten/node_modules/follow-redirects/index.js:84:1)
    at FormData.ondata (internal/streams/legacy.js:19:31)
    at FormData.emit (events.js:314:20)
    at FormData.CombinedStream.write (/home/node/app/webpack:/quinten/node_modules/combined-stream/lib/combined_stream.js:138:1)
    at FormData.CombinedStream._pipeNext (/home/node/app/webpack:/quinten/node_modules/combined-stream/lib/combined_stream.js:126:1)
    at FormData.CombinedStream._realGetNext (/home/node/app/webpack:/quinten/node_modules/combined-stream/lib/combined_stream.js:99:1)
    at FormData.CombinedStream._getNext (/home/node/app/webpack:/quinten/node_modules/combined-stream/lib/combined_stream.js:82:1)
    at DelayedStream.emit (events.js:326:22)
    at DelayedStream._handleEmit (/home/node/app/webpack:/quinten/node_modules/delayed-stream/lib/delayed_stream.js:82:1)
    at Readable.source.emit (/home/node/app/webpack:/quinten/node_modules/delayed-stream/lib/delayed_stream.js:29:1) 

```

**Comment by furryboffin** [comment]
I just tried with node 16, I get the same error. Maybe you could let me know which versions of deps are required?

**Comment by furryboffin** [comment]
The error is now slightly different:
the request data for the file upload:
```
{
  applicantId: '9dfcb38d-b971-4857-87c5-9c55e6273f45',
  file: {
    contents: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    filepath: 'image.jpg',
    contentType: 'image/jpg'
  },
  type: 'passport',
  issuingCountry: 'AND',
  location: { ipAddress: '159.100.251.149', countryOfResidence: 'AND' }
}```

error

OnfidoApiError: Please provide applicant location before starting a check (status code 422) | {}

**Comment by dvacca** [comment]
Hello @furryboffin,
We've tried to reproduce the issue on our side but unfortunately we can't. It looks like the initial error you experienced _data should be a string, Buffer or Uint8Array_ has been solved already. 

With regards to the error you're getting right now, typically it is returned when location is missing (as in documentation [here](https://documentation.onfido.com/#error-codes-and-what-to-do)):

```422 missing_applicant_location	Make sure you've provided the applicant's [location](https://documentation.onfido.com/#location-create-applicant) before starting a check```

While we're digging more, could you please check if providing location at [applicant](https://documentation.onfido.com/#applicant-object) creation time solves the issue? Thanks!

**Comment by dvacca** [comment]
Hello @furryboffin,
The issue you've spotted out should now have been fixed.
Could you please check on your side if it works now?

**Comment by dvacca** [comment]
Hello @furryboffin,
As we didn't get any feedback so far, we assume issue is now solved.

Please reopen it if issue persist.
