### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'name') while file upload

### ISSUE THREAD

**Issue by amitYoair** [onfido/onfido-node#93]
#### What was the expected behaviour?
It should upload a file on onfido.
#### What happened instead?
TypeError: Cannot read properties of null (reading 'name') getting this error trying to upload file on onfido using node sdk.
#### Version info:

- `onfido-node` version:2.6.0
- `node js` version: 16.9.0

#### Code snippet to reproduce:
onfido.document.upload({
      applicantId: applicant.id,
      file: fs.createReadStream("filepath"),
      type: "driving_licence"
});

#### Other useful info:

_screenshots, videos, etc._

**Comment by dvacca** [comment]
Hello @amitYoair,
Unfortunately I can't reproduce your issue. Anyway there is no `name` property in the object you get back from this call. To access the file name, you should instead use the `fileName` property, e.g.:

```node
var document = onfido.document.upload({
  applicantId: applicant.id,
  file: fs.createReadStream("filepath"),
  type: "driving_licence"
});
console.log(document.fileName)
```
I hope it helps.

**Comment by amitYoair** [comment]
TypeError: Cannot read properties of null (reading 'name')
    at FormData._getContentDisposition (/node_modules/@onfido/api/node_modules/form-data/lib/form_data.js:226:40)
    at FormData._multiPartHeader (/node_modules/@onfido/api/node_modules/form-data/lib/form_data.js:177:33)
    at FormData.append (/node_modules/@onfido/api/node_modules/form-data/lib/form_data.js:70:21)
    at /node_modules/@onfido/api/dist/index.js:106:30
    at Array.reduce (<anonymous>)
    at toFormData (/node_modules/@onfido/api/dist/index.js:98:35)
    at Documents.upload (/node_modules/@onfido/api/dist/index.js:191:26)
    at Documents.upload (/node_modules/@onfido/api/dist/index.js:301:22)

**Comment by Gwojda** [comment]
Hi,
Got the same issue, did you find a way to solve this error @amitYoair ?
Thanks,
